name: testStep
on:
 workflow_dispatch

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        id : "step1"
        run: echo Hello from Octo Organization
             my_var=failure
             echo "Output $my_var"
             echo"my_var=$my_var" >> $GITHUB_OUTPUT
      - name: Run another script
        id : "step2"
        run : echo hello again
              echo "Output [${{steps.step1.outputs.my_var}}]"
