name: testStep
on:
 workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        id : step1
        run: echo Hello from Octo Organization
      - name: Run another script
        id : step2
        run : echo hello again
              echo "more info ${{join(steps.step1.outputs.*, '\n')}}"
